replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent
  pullSecret: ""

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: null

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

httpRoute:
  enabled: false
  annotations: {}
  parentRefs: []
  hostnames: []
  rules: []

django:
  debug: "False"
  allowedHosts: "*"
